### ISSUE TITLE
Chromosome order potential issue

### ISSUE THREAD

**Issue by potulabe** [deeptools/pyBigWig#152]
I'm not sure if this kind of problem has been already reported, but I couldn't find any clues on how to solve it, so decided to write my question here.
I made a bunch of bigwig files using [bedGraphToBigWig](https://www.encodeproject.org/software/bedgraphtobigwig/) tool.
The chromosome order in my bedgraph files was right (Chr1...Chr9,Chr10,..). When converting the files, I also provided the chrom.sizes file with right chromosome order.

I can open the bigWig files in the IGV browser, and they look OK, I can browse to any position and the information is displayed correctly.
But when I open the files with pyBigWig, for some reason Chr10 can't be accessed. I'm not sure, but can it be related to the chromosome order problem? Because when I display the chromosome order with ```bw.chroms()``` command, I get the wrong alphabetical order (which was not originally in bedGraph files, and doesn't correspond to the genome file chromosome order): 
```
{'Chr1': 217471166,
 'Chr10': 52432566,
 'Chr2': 181034961,
 'Chr3': 153873357,
 'Chr4': 153961319,
...
}
```
ucsc's bigWigInfo returns also the alphabetical order (despite the chrom.sizes file I provided for bedGraphToBigWig the chromosome order was correct):
```
 ~/projs/ucsc_tools/bigWigInfo -chroms PNS_female.bedgraph.bw
version: 4
isCompressed: yes
isSwapped: 0
primaryDataSize: 879,143
primaryIndexSize: 7,244
zoomLevels: 9
chromCount: 34
        Chr1 0 217471166
        Chr10 1 52432566
        Chr2 2 181034961
        Chr3 3 153873357
        Chr4 4 153961319
        Chr5 5 164033575
        Chr6 6 154486312
        Chr7 7 133565930
        Chr8 8 147241510
        Chr9 9 91218944
        Sca1 10 82299
        Sca109 11 2779
        Sca11 12 53911
        Sca110 13 2622
        Sca124 14 1584
        Sca148 15 991
        Sca151 16 803
        Sca19 17 32064
        Sca2 18 79987
        Sca20 19 31817
        Sca23 20 29586
        Sca29 21 27006
        Sca4 22 61141
        Sca41 23 13206
        Sca46 24 10342
        Sca47 25 10052
        Sca52 26 7253
        Sca59 27 6523
        Sca64 28 5339
        Sca72 29 4995
        Sca75 30 4956
        Sca80 31 4807
        Sca87 32 4214
        Sca94 33 3579
basesCovered: 4,010,903
mean: -nan
min: 0.000000
max: inf
std: -nan
```

I can send the examples of bedGraph and bigwig files if they are needed.

**Comment by dpryan79** [comment]
Sending an example bigwig could be useful. The dictionary order in python isn't always guaranteed, depending on the version of python you're using.

**Comment by potulabe** [comment]
Thank you for answering!
I understand that dictionary order is not guaranteed, but that shouldn't impede accessing the data, isn't it?

[Here](https://drive.google.com/drive/folders/1ciSomVGVDDgV-X-_K_dFxdBTnz67tdnQ?usp=sharing) in the google drive folder there are:
- a small toy example of a bedGraph with 2 regions: one on chr2 and the other on chr10:
```
track type=bedGraph name=test description=test visibility=fullcolor=200,100,0 altColor=0,100,200 priority=20
Chr1	55080	55111	0.16707633
Chr2	336493	336505	0.7326518
Chr10	338640	338652	0.7326518
```

- the bigwig, made from this bedGraph with [bedGraphToBigWig](https://www.encodeproject.org/software/bedgraphtobigwig/) tool (`./bedGraphToBigWig test.bedgraph test.fasta.sizes test.bedgraph.bw`)

When I open this bigwig with pyBigWig I get None on the Chr10:
![image](https://github.com/user-attachments/assets/41580244-d48b-4d1b-822e-767bdabfbd0d)


In IGVjs browser, embedded in my Dash application, I get smth on the Chr10:
- Chr1: 
![image](https://github.com/user-attachments/assets/25e2483a-b7ab-45fd-8060-954b2790c89d)
- Chr2: 
![image](https://github.com/user-attachments/assets/79cc450f-8899-45df-bc5a-36c17aa1bf5b)
- Chr10: 
![image](https://github.com/user-attachments/assets/64e4682d-83ba-4af1-ab9f-1af60594ca02)

**Comment by bmm514** [comment]
I am also having this issue, chromosomes 10 - 22 do not have any data when using pyBigWig!

**Comment by VonAlphaBisZulu** [comment]
Same issue here. All single-digit chromosomes are fine, the double digits return None. This breaks many functions from the deepTools package.

**Comment by VonAlphaBisZulu** [comment]
I tried to fix this with pull request #154. Feel free to test the fix by installing it from my github fork. Who knows if this gets accepted.

**Comment by dpryan79** [comment]
Thanks @potulabe  and @VonAlphaBisZulu , I can fully reproduce this and am currently trying to determine if the issue is in pyBigWig or libBigWig. I'll hopefully have an update shortly.

**Comment by VonAlphaBisZulu** [comment]
Please see the fix to pyBigWig I proposed in the pull request #154

**Comment by dpryan79** [comment]
This is intersting and it used to be impossible to bigWig files like this with most tools, which is why it wasn't supported by libBigWig. The root cause of this is a mismatch between the order of the chromosomes in the header of the bigWig, which is in lexicographic order and the data section where the data blocks are NOT in lexicographic order. At least in older versions of most tools used to create bigWigs this sort of thing would have resulted in an error. Apparently that's no longer the case, which I find questionable but I guess so it goes. @VonAlphaBisZulu basically resolved in in his PR, but I'll make a new one with a few minorish differences and also push this upstream to libBigWig.

Note that files without a mismatch in order between the header and the data should be unaffected by this.

**Comment by dpryan79** [comment]
I'll have a release tagged with this fixed momentarilly.

**Comment by VonAlphaBisZulu** [comment]
@dpryan79 I'd like to reopen this issue.

I updated my pyBigWig from this GitHub repo with your new changes. It has worked great for most cases. In some cases, however, it still doesn't read values when the chromosome order is lexicographic. Here is a small [example bigWig](https://github.com/user-attachments/files/18537843/test2.bw.zip).

This was created with USCS bedGraphToBigwig using the chromosome sizes in chrNameLength.txt created during STAR indexing of hg19. Loading the bigWig into IGV shows signal on all chromosomes.

If I do

```
import pyBigWig
bw = pyBigWig.open("./test2.bw")
{chr : bw.values(chr, 10247780, 10247781) for chr in ['chr1','chr2','chr10','chr12','chrX']}
```

this returns a dict of `NaNs`.

If I look at it with BigWigInfo, it shows:

```
$ bigWigInfo -chroms test2.bw
version: 4
isCompressed: yes
isSwapped: 0
primaryDataSize: 1,661,513
primaryIndexSize: 20,932
zoomLevels: 7
chromCount: 76
        chr1 0 249250621
        chr10 1 135534747
        chr11 2 135006516
        chr11_gl000202_random 3 40103
        chr12 4 133851895
        chr13 5 115169878
        chr14 6 107349540
        chr15 7 102531392
        chr16 8 90354753
        chr17 9 81195210
        chr17_ctg5_hap1 10 1680828
        chr17_gl000203_random 11 37498
        chr17_gl000204_random 12 81310
        chr17_gl000205_random 13 174588
        chr18 14 78077248
        chr18_gl000207_random 15 4262
        chr19 16 59128983
        chr19_gl000208_random 17 92689
        chr19_gl000209_random 18 159169
        chr1_gl000191_random 19 106433
        chr1_gl000192_random 20 547496
        chr2 21 243199373
        chr20 22 63025520
        chr21 23 48129895
        chr22 24 51304566
        chr3 25 198022430
        chr4 26 191154276
        chr4_ctg9_hap1 27 590426
        chr4_gl000193_random 28 189789
        chr4_gl000194_random 29 191469
        chr5 30 180915260
        chr6 31 171115067
        chr6_apd_hap1 32 4622290
        chr6_cox_hap2 33 4795371
        chr6_dbb_hap3 34 4610396
        chr6_mann_hap4 35 4683263
        chr6_mcf_hap5 36 4833398
        chr6_qbl_hap6 37 4611984
        chr6_ssto_hap7 38 4928567
        chr7 39 159138663
        chr7_gl000195_random 40 182896
        chr8 41 146364022
        chr9 42 141213431
        chr9_gl000198_random 43 90085
        chr9_gl000199_random 44 169874
        chrUn_gl000211 45 166566
        chrUn_gl000212 46 186858
        chrUn_gl000213 47 164239
        chrUn_gl000214 48 137718
        chrUn_gl000216 49 172294
        chrUn_gl000217 50 172149
        chrUn_gl000218 51 161147
        chrUn_gl000219 52 179198
        chrUn_gl000220 53 161802
        chrUn_gl000221 54 155397
        chrUn_gl000222 55 186861
        chrUn_gl000223 56 180455
        chrUn_gl000224 57 179693
        chrUn_gl000225 58 211173
        chrUn_gl000226 59 15008
        chrUn_gl000227 60 128374
        chrUn_gl000228 61 129120
        chrUn_gl000229 62 19913
        chrUn_gl000230 63 43691
        chrUn_gl000231 64 27386
        chrUn_gl000232 65 40652
        chrUn_gl000233 66 45941
        chrUn_gl000234 67 40531
        chrUn_gl000235 68 34474
        chrUn_gl000237 69 45867
        chrUn_gl000239 70 33824
        chrUn_gl000240 71 41933
        chrUn_gl000241 72 42152
        chrUn_gl000243 73 43341
        chrX 74 155270560
        chrY 75 59373566
basesCovered: 35,008,174
mean: 0.999623
min: 0.989070
max: 10.879800
std: 0.117345
```

**Comment by VonAlphaBisZulu** [comment]
Okay. That's on me. When there are intervals with undefined values, they are not assumed to be 0, which makes sense. My bedgraphs should not be gapped.
